apiVersion: v1
kind: Pod 
metadata: 
  name: nginx
  labels: 
    app: web # attached to our pod, we need that later
spec:
  containers: 
    - name: nginx
      image: nginx:1.27.5-alpine
      ports: 
        - containerPort: 80
